clc, clear, close all
%% Data: Voltage, Resistances, Calculated Currents
U = 1:20;

R1 = 10;
R2 = 20;
R3 = 30;

I1 = U / R1;
I2 = U / R2;
I3 = U / R3;

%% Plots
plot(U, I1, 'r', ...
    'LineWidth', 2, ...
    'LineStyle', '-.', ...
    'Marker', 'o', ...
    'MarkerEdgeColor', 'g')

hold on
plot(U, I2, 'g', ...
    'LineWidth', 2, ...
    'LineStyle', '--', ...
    'Marker', '*', ...
    'MarkerEdgecolor', 'r')

plot(U, I3, 'b', ...
    'LineWidth', 2, ...
    'LineStyle', '-.', ...
    'Marker', '^', ...
    'MarkerEdgecolor', 'b')

%% Labels, Limits, Grid
% Labels
xlabel( ...
    'Voltage', ...
    'FontSize', 12, ...
    'FontWeight', 'Bold', ...
    'Color', 'r')

ylabel( ...
    'Current', ...
    'FontSize', 12, ...
    'FontWeight', 'Bold', ...
    'Color', 'b')

% Limits
xLimMin = min(U) - min(U) * 0.3;
xLimMax = max(U) + max(U) * 0.1;
allYValues = [I1 I2 I3];
yLimMin = min(allYValues) - min(allYValues) * 0.9;
yLimMax = max(allYValues) + max(allYValues) * 0.1;
xlim([xLimMin xLimMax])
ylim([yLimMin yLimMax])

% Grid
grid on
grid minor

%% Legend and Title
legend(...
    {'R_1 = 10 Ohm', 'R_2 = 20 Ohm', 'R_3 = 30 Ohm'}, ...
    'FontSize', 15, ...
    'FontWeight', 'bold', ...
    'TextColor', 'k', ...
    'Location', 'northwest', ...
    'Orientation', 'vertical', ...
    'Box', 'off')

title('Change in Current for R_1, R_2 and R_3', ...
    'FontSize', 15, ...
    'FontWeight', 'bold')
